### ISSUE TITLE
Plugin fails in Sonarqube 5.6.3

### ISSUE THREAD

**Issue by rschaeferhig** [galexandre/sonar-cobertura#12]
One of my customers has a Java app with two folders containing many of the same files/classes:
*PaymentProcessorWeb
*PaymentProcessorV2Web

They point Cobertura at PaymentProcessorV2Web and create a coverage.xml file. The file is picked up in Sonarqube. The file's "source" property points to PaymentProcessorV2Web but the failure message says:

java.lang.IllegalStateException: Can't create measure for line 467 for file 'D:/a6/pi_paymentprocessor/autobuild_v1_0/trunk/src/PaymentProcessorWeb/src/com/thehartford/consumer/ams/AbstractBaseProxy.java' with 459 lines

It appears the plugin is looking at PaymentProcessorWeb (not "V2") and failing. We've also set Sonarqube sonar.sources=PaymentProcessorV2Web and sonar.exclusions=PaymentProcessorWeb for what it's worth.

Any thoughts?

I've included the Sonarqube log, build.xml and coverage.xml. 
[log (1).txt](https://github.com/galexandre/sonar-cobertura/files/1145879/log.1.txt)

[build.xml.txt](https://github.com/galexandre/sonar-cobertura/files/1145888/build.xml.txt)
[coverage.xml.txt](https://github.com/galexandre/sonar-cobertura/files/1145889/coverage.xml.txt)

**Comment by galexandre** [comment]
Hi @rschaeferhig, 

I will have a look ASAP.

Regards

**Comment by rschaeferhig** [comment]
Thanks @galexandre. Let me know if you need more info.
