### ISSUE TITLE
Scan sources by Sonar Scanner and push results to SonarCloud

### ISSUE THREAD

**Issue by agabrys** [galexandre/sonar-cobertura#21]
Hello,
I requested to update the plugin in SonarQube update center (see [the request](https://community.sonarsource.com/t/new-release-cobertura-1-8-1-9-1-9-1-and-2-0/789?u=agabrys)).

G Ann Campbell answered:

>  I don’t see this project on SonarCloud, and a green QG is a requirement

Please execute Sonar Scanner analysis and push results to SonarCloud. It allows upgrading plugin form SonarQube marketplace instead of manual installation.

Cheers

**Comment by galexandre** [comment]
Hi,

Thank you for having open a ticket for the release, I was extremly busy recently. 
I answered the ticket you opened, I found an issue with the analysis (locally).

**Comment by galexandre** [comment]
Hi,

The plugin has been published.

Regards,

galexandre
