### ISSUE TITLE
Build Instruction.

### ISSUE THREAD

**Issue by niharbabu99** [galexandre/sonar-cobertura#26]
Can someone please provide build instructions.

**Comment by niharbabu99** [comment]
due to maven config issue i was not able to build. If some one can create a document on how to use it will be very useful. I see a travis.sh file in the project, if possible request some to provide info on the same.

**Comment by galexandre** [comment]
Hi! 
Travis is called every time you do a PR. If you want to build locally the artifact, use the following maven command:
```mvn clean install```
