### ISSUE TITLE
Plugin Cobertura [cobertura] is ignored during installation of plugin in SonarQube

### ISSUE THREAD

**Issue by srisaravananwt** [galexandre/sonar-cobertura#27]
Using following versions,
1. SonarQube Version 6.7 (build 33306)
2. SonarJava plugin 4.15.0.12310
3. sonar-cobertura-plugin-2.0.jar 

When I place the sonar-cobertura-plugin-2.0.jar in /extensions/plugins directory and started the SonarQube server. I am getting below warning and server is not getting started.

2019.01.07 11:18:51 WARN  web[][o.s.s.p.ServerPluginRepository] Plugin Cobertura [cobertura] is ignored because the version java of required plugin [5.1.0.13090] is not supported

**Comment by galexandre** [comment]
Hello, 

It seems you need to upgrade the version of the Java plugin. Minimum 5.1.

Regards,

G
