### ISSUE TITLE
Sonarqube 7.5 support?

### ISSUE THREAD

**Issue by rschaeferhig** [galexandre/sonar-cobertura#29]
We're just upgraded to Sonarqube 7.5 with SonarJava 5.9.2. It appears we cannot install the Cobertura plugin. I get "no compatible plugin found". Is this a problem with this version of Sonarqube or SonarJava?

**Comment by galexandre** [comment]
Hi,
I will investigate this week.

**Comment by galexandre** [comment]
Hi,

I installed the plugin without any issues using the community version (7.5 and 7.7).

**Comment by rschaeferhig** [comment]
I get the attached error when trying to install on 7.5 Enterprise.
![Cobertura_Error](https://user-images.githubusercontent.com/7859432/55321674-4562eb80-5448-11e9-93e6-c8dc28dbf391.png)

**Comment by galexandre** [comment]
What if you remove/move the plugin from the folder and re install it?

**Comment by rschaeferhig** [comment]
There isn't one.. :|
![plugins](https://user-images.githubusercontent.com/7859432/55323660-b527a500-544d-11e9-8444-de66e94ff297.png)

**Comment by galexandre** [comment]
I see, this is a bit strange. Is all your plugins up to date?

**Comment by rschaeferhig** [comment]
As far as I know. This upgrade install was done just about a month ago. I installed all the non-standard plugins at that time.

**Comment by galexandre** [comment]
Your version of the SonarJava plugin seems not up to date.
![Screenshot 2019-04-01 at 13 56 46](https://user-images.githubusercontent.com/3588802/55329279-19fef180-5486-11e9-9f78-d3a0abfd1800.png)

**Comment by rschaeferhig** [comment]
Very odd. All my plugins list higher versions but I have no option to update them. If I hover over the new version of the plugin it says "Requires system update". I'll open a Sonarqube support ticket. Thanks.
![plugins-installed](https://user-images.githubusercontent.com/7859432/55329578-f5425400-545c-11e9-9e29-81e7444974b0.png)

**Comment by galexandre** [comment]
You're welcome. Let me know about the outcome of your ticket.

**Comment by rschaeferhig** [comment]
So, this is a fun one. We found a bug in Sonarqube Enterprise 7.5. We needed a quick fix. Sonarqube agreed to do a 7.5.1 *just for us* to fix the specific bug. Since 7.5.1 is not registered with Marketplace as a valid version we can't upgrade plugins through the Marketplace. We have to either install/upgrade our plugins manually or move to 7.7.  

Thanks for your help.

**Comment by galexandre** [comment]
Great, thanks for the update about the bug!
