### ISSUE TITLE
Fix compatibility with SQ 6.1+

### ISSUE THREAD

**Issue by henryju** [galexandre/sonar-cobertura#4]
Plugin is using deprecated APIs that will be removed in SonarQube 6.x like org.sonar.api.scan.filesystem.ModuleFileSystem
https://jira.sonarsource.com/browse/SONAR-7864

**Comment by larsauswsw** [comment]
+1

**Comment by jplock** [comment]
Is anyone able to merge this in and publish a new release?

**Comment by henryju** [comment]
Anyone can candidate on SonarQube Google group to become maintainer of this plugin.

**Comment by charpour** [comment]
any ideas if anyone is going to take this one?
